// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_NEW_API_KEY_FROM_GOOGLE_SERVICES_JSON',
    appId: '1:477405059891:android:d38bc46dcbeb60b54d7c46',
    messagingSenderId: '477405059891',
    projectId: 'digitallamicomnp',
    databaseURL: 'https://digitallamicomnp-default-rtdb.firebaseio.com',
    storageBucket: 'digitallamicomnp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_NEW_API_KEY_FROM_GOOGLESERVICE_INFO_PLIST',
    appId: '1:477405059891:ios:bfc486eb584d03ed4d7c46',
    messagingSenderId: '477405059891',
    projectId: 'digitallamicomnp',
    databaseURL: 'https://digitallamicomnp-default-rtdb.firebaseio.com',
    storageBucket: 'digitallamicomnp.firebasestorage.app',
    iosClientId: 'REPLACE_WITH_NEW_IOS_CLIENT_ID',
    iosBundleId: 'com.digitallami.appz',
  );

  // TODO: Replace the placeholder values below with your Firebase web app
  // configuration from Firebase Console → Project Settings → Your apps → Web app.
  // Run `flutterfire configure` to auto-generate these values.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: '477405059891',
    projectId: 'digitallamicomnp',
    authDomain: 'digitallamicomnp.firebaseapp.com',
    databaseURL: 'https://digitallamicomnp-default-rtdb.firebaseio.com',
    storageBucket: 'digitallamicomnp.firebasestorage.app',
    measurementId: 'REPLACE_WITH_MEASUREMENT_ID',
  );
}
